---
### handlers file for ansible-cassandra for tarball installations
#- name: "restart cassandra"
#  shell: bash -x /opt/apache-cassandra-3.9/bin/cassandra -R 
#  async: 6000
#  poll: 0

- name: "restart cassandra"
  service:
    name: "cassandra"
    state: "restarted"
